/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import ciudadesdepartamentos.BDCiudad;
import ciudadesdepartamentos.Ciudad;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CONTROLSALA
 */
public class ModuloCiudades extends javax.swing.JFrame {

    /**
     * Creates new form ModuloCiudades
     */
    public ModuloCiudades() {
        initComponents();
        cargarCiudades();
    }
    BDCiudad bdc =new BDCiudad();

    ModuloCiudades() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfIdCiudad = new javax.swing.JTextField();
        tfNombreCiudad = new javax.swing.JTextField();
        tfIdDepartamento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tCiudades = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnRegreso = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnIngresar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfNombreCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreCiudadActionPerformed(evt);
            }
        });

        jLabel1.setText("id_ciudad");

        jLabel2.setText("nombre_ciudad");

        jLabel3.setText("id_departamento");

        tCiudades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id_ciudad", "nombre _ciudad", "id_departamento"
            }
        ));
        tCiudades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tCiudadesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tCiudadesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tCiudades);

        jLabel4.setText("Ciudades");

        btnRegreso.setText("regreso");
        btnRegreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresoActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEditar.setText("editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnIngresar1.setText("ingresar");
        btnIngresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnIngresar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tfIdDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                            .addComponent(tfNombreCiudad)
                                            .addComponent(tfIdCiudad)))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnBuscar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegreso))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfIdCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNombreCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfIdDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditar)
                            .addComponent(btnEliminar)
                            .addComponent(btnIngresar1)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btnRegreso))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNombreCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreCiudadActionPerformed

    private void btnRegresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresoActionPerformed
        this.setVisible(false);
        VentanaPrincipal VP =new  VentanaPrincipal();
        VP.setVisible(true);
    }//GEN-LAST:event_btnRegresoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String txtIdCiudad = JOptionPane.showInputDialog("Ingrese Id de ciudad");
        try
       {
          bdc.buscarCiudad(txtIdCiudad);
          //System.out.println(str.toString());
       } catch (Exception e)
       {
           System.out.println("Alguna cosa");
       }
        
    
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
         String txtIdCiudad, txtNombreCiudad,txtIdDepartamento;
         
         txtIdCiudad=tfIdCiudad.getText();
         txtNombreCiudad=tfNombreCiudad.getText();
         txtIdDepartamento=tfIdDepartamento.getText();
         
         if(txtIdCiudad.isEmpty()||txtNombreCiudad.isEmpty()||txtIdDepartamento.isEmpty() ){
             JOptionPane.showMessageDialog(this,"Campos vacios");
            
         }else{
             try{
                 Ciudad c1 =new Ciudad(txtIdCiudad, txtNombreCiudad,txtIdDepartamento);
                 bdc.editarCiudad(c1);
                 limpiar();
                 cargarCiudades();
                 tfIdCiudad.setEnabled(true);
                 btnBuscar.setEnabled(true);
                 
                } catch (Exception e) {
                
                }
        
        cargarCiudades();
        
       
         }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void tCiudadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tCiudadesMouseClicked
    int fila =tCiudades.getSelectedRow();
    tfIdCiudad.setText(tCiudades.getValueAt(fila, 0).toString());
    tfNombreCiudad.setText(tCiudades.getValueAt(fila, 1).toString());
    tfIdDepartamento.setText(tCiudades.getValueAt(fila, 2).toString());
    
   tfIdCiudad.setEnabled(false);
   btnBuscar.setEnabled(false);
      
    }//GEN-LAST:event_tCiudadesMouseClicked

    private void tCiudadesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tCiudadesMousePressed
       // TODO add your handling code here:
    }//GEN-LAST:event_tCiudadesMousePressed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String  txtIdCiudad;
        txtIdCiudad=tfIdCiudad.getText();
        if(txtIdCiudad.isEmpty()){
            
            JOptionPane.showMessageDialog(null, "selecione una ciudad");
       
        }else{
             try {
            
            bdc.deleteCiudad(txtIdCiudad);
            cargarCiudades();
            tfIdCiudad.setEnabled(true);
            btnBuscar.setEnabled(true);
            limpiar();
           
            
            
            } 
            catch (Exception e) {
                
            }
        }
      
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnIngresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresar1ActionPerformed
          String txtIdCiudad, txtNombreCiudad,txtIdDepartamento;
         
         txtIdCiudad=tfIdCiudad.getText();
         txtNombreCiudad=tfNombreCiudad.getText();
         txtIdDepartamento=tfIdDepartamento.getText();
         
         if(txtIdCiudad.isEmpty()||txtNombreCiudad.isEmpty()||txtIdDepartamento.isEmpty() ){
             JOptionPane.showMessageDialog(this,"Campos vacios");
            
         }else{
             try{
                 Ciudad c1 =new Ciudad(txtIdCiudad, txtNombreCiudad,txtIdDepartamento);
                 bdc.insertarCiudad(c1);
                 cargarCiudades();
                 tfIdCiudad.setEnabled(true);
                 btnBuscar.setEnabled(true);
                 
                } catch (Exception e) {
                
                }
        
        cargarCiudades();
        
       
         } }
        //  TODO add your handling code here:         String txtIdCiudad, txtNombreCiudad,txtIdDepartamento;
         
         
    private void limpiar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void cargarCiudades() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    }//GEN-LAST:event_btnIngresar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModuloCiudades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModuloCiudades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModuloCiudades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModuloCiudades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModuloCiudades().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnIngresar1;
    private javax.swing.JButton btnRegreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tCiudades;
    private javax.swing.JTextField tfIdCiudad;
    private javax.swing.JTextField tfIdDepartamento;
    private javax.swing.JTextField tfNombreCiudad;
    // End of variables declaration//GEN-END:variables

    private void cargarCiudades() {


    DefaultTableModel modeloCiudades =new DefaultTableModel();
    modeloCiudades= bdc.getCiudades();
    tCiudades.setModel(modeloCiudades);
    
    

    }

    private void limpiar() {
        tfNombreCiudad.setText(null);
        tfIdCiudad.setText(null);
        tfIdDepartamento.setText(null);
    }
}
